CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    student_number VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT uq_app_user_student_number UNIQUE (student_number),
    CONSTRAINT ck_app_user_email_normalized
        CHECK (email = LOWER(BTRIM(email))),
    CONSTRAINT ck_app_user_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_user_roles_role
        CHECK (role IN ('RESIDENT', 'WORKER', 'ADMIN', 'SUPER_ADMIN'))
);

CREATE INDEX ix_user_roles_role
    ON user_roles (role);

CREATE TABLE refresh_token_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    token_hash BYTEA NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_refresh_token_sessions PRIMARY KEY (id),
    CONSTRAINT fk_refresh_token_sessions_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT uq_refresh_token_sessions_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_token_sessions_token_hash_length
        CHECK (OCTET_LENGTH(token_hash) = 32),
    CONSTRAINT ck_refresh_token_sessions_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT ck_refresh_token_sessions_revocation
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX ix_refresh_token_sessions_user_id
    ON refresh_token_sessions (user_id);
