CREATE TABLE dormitory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_dormitory PRIMARY KEY (id)
);

CREATE TABLE building (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dormitory_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_building PRIMARY KEY (id),
    CONSTRAINT fk_building_dormitory
        FOREIGN KEY (dormitory_id) REFERENCES dormitory (id) ON DELETE RESTRICT,
    CONSTRAINT uq_building_dormitory_code UNIQUE (dormitory_id, code)
);

CREATE TABLE space (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    building_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,
    floor INTEGER NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_space PRIMARY KEY (id),
    CONSTRAINT fk_space_building
        FOREIGN KEY (building_id) REFERENCES building (id) ON DELETE RESTRICT,
    CONSTRAINT uq_space_building_code UNIQUE (building_id, code),
    CONSTRAINT ck_space_type
        CHECK (type IN ('ROOM', 'CORRIDOR', 'LOUNGE', 'LAUNDRY_ROOM', 'RESTROOM',
                        'LOBBY', 'KITCHEN', 'STUDY_ROOM', 'OTHER'))
);

CREATE TABLE facility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    space_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    facility_type VARCHAR(50) NOT NULL,
    asset_code VARCHAR(100),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    installed_at DATE,
    description VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_facility PRIMARY KEY (id),
    CONSTRAINT fk_facility_space
        FOREIGN KEY (space_id) REFERENCES space (id) ON DELETE RESTRICT,
    CONSTRAINT uq_facility_asset_code UNIQUE (asset_code),
    CONSTRAINT ck_facility_status
        CHECK (status IN ('ACTIVE', 'OUT_OF_SERVICE', 'RETIRED'))
);

CREATE INDEX ix_facility_space_id
    ON facility (space_id);

CREATE TABLE maintenance_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id BIGINT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    default_priority VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_maintenance_category PRIMARY KEY (id),
    CONSTRAINT fk_maintenance_category_parent
        FOREIGN KEY (parent_id) REFERENCES maintenance_category (id) ON DELETE RESTRICT,
    CONSTRAINT uq_maintenance_category_code UNIQUE (code),
    CONSTRAINT ck_maintenance_category_not_self_parent
        CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_maintenance_category_default_priority
        CHECK (default_priority IN ('LOW', 'NORMAL', 'HIGH', 'EMERGENCY'))
);

CREATE INDEX ix_maintenance_category_parent_id
    ON maintenance_category (parent_id);
