CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE residence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resident_id BIGINT NOT NULL,
    room_space_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_residence PRIMARY KEY (id),
    CONSTRAINT fk_residence_resident FOREIGN KEY (resident_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_residence_room_space FOREIGN KEY (room_space_id) REFERENCES space (id) ON DELETE RESTRICT,
    CONSTRAINT ck_residence_date_range CHECK (end_date IS NULL OR start_date < end_date),
    CONSTRAINT ex_residence_resident_period EXCLUDE USING gist
        (resident_id WITH =, daterange(start_date, end_date, '[)') WITH &&)
);

CREATE INDEX ix_residence_room_space_start_date ON residence (room_space_id, start_date DESC);
CREATE INDEX ix_residence_resident_start_date ON residence (resident_id, start_date DESC);
