CREATE TABLE maintenance_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_number VARCHAR(30) NOT NULL,
    reporter_id BIGINT NOT NULL,
    space_id BIGINT NOT NULL,
    facility_id BIGINT,
    category_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    entry_policy VARCHAR(40) NOT NULL,
    contact_before_entry BOOLEAN NOT NULL,
    preferred_visit_start TIMESTAMPTZ,
    preferred_visit_end TIMESTAMPTZ,
    duplicate_of_id BIGINT,
    status_reason VARCHAR(500),
    resolved_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_maintenance_request PRIMARY KEY (id),
    CONSTRAINT uq_maintenance_request_number UNIQUE (request_number),
    CONSTRAINT fk_maintenance_request_reporter FOREIGN KEY (reporter_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_maintenance_request_space FOREIGN KEY (space_id) REFERENCES space (id) ON DELETE RESTRICT,
    CONSTRAINT fk_maintenance_request_facility FOREIGN KEY (facility_id) REFERENCES facility (id) ON DELETE RESTRICT,
    CONSTRAINT fk_maintenance_request_category FOREIGN KEY (category_id) REFERENCES maintenance_category (id) ON DELETE RESTRICT,
    CONSTRAINT fk_maintenance_request_duplicate FOREIGN KEY (duplicate_of_id) REFERENCES maintenance_request (id) ON DELETE RESTRICT,
    CONSTRAINT ck_maintenance_request_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'EMERGENCY')),
    CONSTRAINT ck_maintenance_request_status CHECK (status IN ('REPORTED', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REJECTED', 'DUPLICATE')),
    CONSTRAINT ck_maintenance_request_entry_policy CHECK (entry_policy IN ('RESIDENT_PRESENT_REQUIRED', 'ABSENT_ENTRY_ALLOWED')),
    CONSTRAINT ck_maintenance_request_preferred_time CHECK ((preferred_visit_start IS NULL AND preferred_visit_end IS NULL) OR (preferred_visit_start < preferred_visit_end))
);

CREATE INDEX ix_maintenance_request_status_created_at ON maintenance_request (status, created_at);
CREATE INDEX ix_maintenance_request_space_status ON maintenance_request (space_id, status);
CREATE INDEX ix_maintenance_request_reporter_created_at ON maintenance_request (reporter_id, created_at);
CREATE INDEX ix_maintenance_request_category_created_at ON maintenance_request (category_id, created_at);
CREATE INDEX ix_maintenance_request_priority_status ON maintenance_request (priority, status);

CREATE TABLE request_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id BIGINT NOT NULL,
    actor_id BIGINT,
    event_type VARCHAR(50) NOT NULL,
    previous_status VARCHAR(30),
    new_status VARCHAR(30),
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_request_history PRIMARY KEY (id),
    CONSTRAINT fk_request_history_request FOREIGN KEY (request_id) REFERENCES maintenance_request (id) ON DELETE RESTRICT,
    CONSTRAINT fk_request_history_actor FOREIGN KEY (actor_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_request_history_event_type CHECK (event_type IN ('REQUEST_CREATED')),
    CONSTRAINT ck_request_history_previous_status CHECK (previous_status IS NULL OR previous_status IN ('REPORTED', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REJECTED', 'DUPLICATE')),
    CONSTRAINT ck_request_history_new_status CHECK (new_status IS NULL OR new_status IN ('REPORTED', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REJECTED', 'DUPLICATE'))
);

CREATE INDEX ix_request_history_request_created_at ON request_history (request_id, created_at);
